// Code generated by protoc-gen-go. DO NOT EDIT.
// source: request.proto

package v1

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Expresses the result of a report call.
type RequestResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestResult) Reset()         { *m = RequestResult{} }
func (m *RequestResult) String() string { return proto.CompactTextString(m) }
func (*RequestResult) ProtoMessage()    {}
func (*RequestResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{0}
}

func (m *RequestResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestResult.Unmarshal(m, b)
}
func (m *RequestResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestResult.Marshal(b, m, deterministic)
}
func (m *RequestResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestResult.Merge(m, src)
}
func (m *RequestResult) XXX_Size() int {
	return xxx_messageInfo_RequestResult.Size(m)
}
func (m *RequestResult) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestResult.DiscardUnknown(m)
}

var xxx_messageInfo_RequestResult proto.InternalMessageInfo

func init() {
	proto.RegisterType((*RequestResult)(nil), "adapter.model.v1.RequestResult")
}

func init() { proto.RegisterFile("request.proto", fileDescriptor_7f73548e33e655fe) }

var fileDescriptor_7f73548e33e655fe = []byte{
	// 144 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4a, 0x2d, 0x2c,
	0x4d, 0x2d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x48, 0x4c, 0x49, 0x2c, 0x28,
	0x49, 0x2d, 0xd2, 0xcb, 0xcd, 0x4f, 0x49, 0xcd, 0xd1, 0x2b, 0x33, 0x94, 0x92, 0x4c, 0xcf, 0x4f,
	0xcf, 0xd7, 0x07, 0x11, 0x60, 0x15, 0x60, 0x16, 0x44, 0xb1, 0x12, 0x3f, 0x17, 0x6f, 0x10, 0x44,
	0x77, 0x50, 0x6a, 0x71, 0x69, 0x4e, 0x89, 0x93, 0xf5, 0x89, 0x87, 0x72, 0x0c, 0x1f, 0x1e, 0xca,
	0x31, 0xac, 0x78, 0x24, 0xc7, 0x10, 0xa5, 0x9b, 0x9e, 0x59, 0x92, 0x51, 0x9a, 0xa4, 0x97, 0x9c,
	0x9f, 0xab, 0x9f, 0x9c, 0x5f, 0x96, 0x58, 0x94, 0x59, 0x52, 0xa9, 0x9f, 0x9a, 0x9c, 0x91, 0xaf,
	0x9f, 0x58, 0x90, 0xa9, 0x0f, 0xb5, 0x48, 0x1f, 0x6c, 0x91, 0x7e, 0x99, 0x61, 0x12, 0x1b, 0xd8,
	0x50, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xae, 0x3b, 0xbc, 0x02, 0x92, 0x00, 0x00, 0x00,
}
