tracing:
  enabled: false
metrics:
  enabled: false
healthcheck:
  port: 8082
server:
  port: 8080
adapters:
  tcp:
    timeout: 999s
  # http:
  #   ...
reporting:
  prometheus:
    enabled: true
  gcs:
    enabled: true
    bucket: gs://metric-bucket-unique-name-123