// Code generated by protoc-gen-go. DO NOT EDIT.
// source: type.proto

// Describes the rules used to configure Mixer's policy and telemetry features.

package v1alpha1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// An instance field of type Value denotes that the expression for the field is of dynamic type and can evaluate to any
// [ValueType][echo.policy.v1alpha1.ValueType] enum values. For example, when
// authoring an instance configuration for a template that has a field `data` of type `echo.policy.v1alpha1.Value`,
// both of the following expressions are valid `data: source.ip | ip("0.0.0.0")`, `data: request.id | ""`;
// the resulting type is either ValueType.IP_ADDRESS or ValueType.STRING for the two cases respectively.
//
// Objects of type Value are also passed to the adapters during request-time. There is a 1:1 mapping between
// oneof fields in `Value` and enum values inside `ValueType`. Depending on the expression's evaluated `ValueType`,
// the equivalent oneof field in `Value` is populated by Mixer and passed to the adapters.
type Value struct {
	// Types that are valid to be assigned to Value:
	//	*Value_StringValue
	//	*Value_Int64Value
	//	*Value_DoubleValue
	//	*Value_BoolValue
	//	*Value_IpAddressValue
	//	*Value_TimestampValue
	//	*Value_DurationValue
	//	*Value_DnsNameValue
	//	*Value_StringMapValue
	Value                isValue_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eaed4801c3a9059, []int{0}
}

func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

type isValue_Value interface {
	isValue_Value()
}

type Value_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Value_Int64Value struct {
	Int64Value int64 `protobuf:"varint,2,opt,name=int64_value,json=int64Value,proto3,oneof"`
}

type Value_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,3,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type Value_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Value_IpAddressValue struct {
	IpAddressValue *IPAddress `protobuf:"bytes,5,opt,name=ip_address_value,json=ipAddressValue,proto3,oneof"`
}

type Value_TimestampValue struct {
	TimestampValue *TimeStamp `protobuf:"bytes,6,opt,name=timestamp_value,json=timestampValue,proto3,oneof"`
}

type Value_DurationValue struct {
	DurationValue *Duration `protobuf:"bytes,7,opt,name=duration_value,json=durationValue,proto3,oneof"`
}

type Value_DnsNameValue struct {
	DnsNameValue *DNSName `protobuf:"bytes,9,opt,name=dns_name_value,json=dnsNameValue,proto3,oneof"`
}

type Value_StringMapValue struct {
	StringMapValue *StringMap `protobuf:"bytes,11,opt,name=string_map_value,json=stringMapValue,proto3,oneof"`
}

func (*Value_StringValue) isValue_Value() {}

func (*Value_Int64Value) isValue_Value() {}

func (*Value_DoubleValue) isValue_Value() {}

func (*Value_BoolValue) isValue_Value() {}

func (*Value_IpAddressValue) isValue_Value() {}

func (*Value_TimestampValue) isValue_Value() {}

func (*Value_DurationValue) isValue_Value() {}

func (*Value_DnsNameValue) isValue_Value() {}

func (*Value_StringMapValue) isValue_Value() {}

func (m *Value) GetValue() isValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Value) GetStringValue() string {
	if x, ok := m.GetValue().(*Value_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (m *Value) GetInt64Value() int64 {
	if x, ok := m.GetValue().(*Value_Int64Value); ok {
		return x.Int64Value
	}
	return 0
}

func (m *Value) GetDoubleValue() float64 {
	if x, ok := m.GetValue().(*Value_DoubleValue); ok {
		return x.DoubleValue
	}
	return 0
}

func (m *Value) GetBoolValue() bool {
	if x, ok := m.GetValue().(*Value_BoolValue); ok {
		return x.BoolValue
	}
	return false
}

func (m *Value) GetIpAddressValue() *IPAddress {
	if x, ok := m.GetValue().(*Value_IpAddressValue); ok {
		return x.IpAddressValue
	}
	return nil
}

func (m *Value) GetTimestampValue() *TimeStamp {
	if x, ok := m.GetValue().(*Value_TimestampValue); ok {
		return x.TimestampValue
	}
	return nil
}

func (m *Value) GetDurationValue() *Duration {
	if x, ok := m.GetValue().(*Value_DurationValue); ok {
		return x.DurationValue
	}
	return nil
}

func (m *Value) GetDnsNameValue() *DNSName {
	if x, ok := m.GetValue().(*Value_DnsNameValue); ok {
		return x.DnsNameValue
	}
	return nil
}

func (m *Value) GetStringMapValue() *StringMap {
	if x, ok := m.GetValue().(*Value_StringMapValue); ok {
		return x.StringMapValue
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Value) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Value_StringValue)(nil),
		(*Value_Int64Value)(nil),
		(*Value_DoubleValue)(nil),
		(*Value_BoolValue)(nil),
		(*Value_IpAddressValue)(nil),
		(*Value_TimestampValue)(nil),
		(*Value_DurationValue)(nil),
		(*Value_DnsNameValue)(nil),
		(*Value_StringMapValue)(nil),
	}
}

// An instance field of type IPAddress denotes that the expression for the field must evaluate to
// [ValueType.IP_ADDRESS][echo.policy.v1alpha1.ValueType.IP_ADDRESS]
//
// Objects of type IPAddress are also passed to the adapters during request-time for the instance fields of
// type IPAddress
type IPAddress struct {
	// IPAddress encoded as bytes.
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IPAddress) Reset()         { *m = IPAddress{} }
func (m *IPAddress) String() string { return proto.CompactTextString(m) }
func (*IPAddress) ProtoMessage()    {}
func (*IPAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eaed4801c3a9059, []int{1}
}

func (m *IPAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IPAddress.Unmarshal(m, b)
}
func (m *IPAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IPAddress.Marshal(b, m, deterministic)
}
func (m *IPAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IPAddress.Merge(m, src)
}
func (m *IPAddress) XXX_Size() int {
	return xxx_messageInfo_IPAddress.Size(m)
}
func (m *IPAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_IPAddress.DiscardUnknown(m)
}

var xxx_messageInfo_IPAddress proto.InternalMessageInfo

func (m *IPAddress) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

// An instance field of type Duration denotes that the expression for the field must evaluate to
// [ValueType.DURATION][echo.policy.v1alpha1.ValueType.DURATION]
//
// Objects of type Duration are also passed to the adapters during request-time for the instance fields of
// type Duration
type Duration struct {
	// Duration encoded as google.protobuf.Duration.
	Value                *duration.Duration `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Duration) Reset()         { *m = Duration{} }
func (m *Duration) String() string { return proto.CompactTextString(m) }
func (*Duration) ProtoMessage()    {}
func (*Duration) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eaed4801c3a9059, []int{2}
}

func (m *Duration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Duration.Unmarshal(m, b)
}
func (m *Duration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Duration.Marshal(b, m, deterministic)
}
func (m *Duration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Duration.Merge(m, src)
}
func (m *Duration) XXX_Size() int {
	return xxx_messageInfo_Duration.Size(m)
}
func (m *Duration) XXX_DiscardUnknown() {
	xxx_messageInfo_Duration.DiscardUnknown(m)
}

var xxx_messageInfo_Duration proto.InternalMessageInfo

func (m *Duration) GetValue() *duration.Duration {
	if m != nil {
		return m.Value
	}
	return nil
}

// An instance field of type TimeStamp denotes that the expression for the field must evaluate to
// [ValueType.TIMESTAMP][echo.policy.v1alpha1.ValueType.TIMESTAMP]
//
// Objects of type TimeStamp are also passed to the adapters during request-time for the instance fields of
// type TimeStamp
type TimeStamp struct {
	// TimeStamp encoded as google.protobuf.Timestamp.
	Value                *timestamp.Timestamp `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TimeStamp) Reset()         { *m = TimeStamp{} }
func (m *TimeStamp) String() string { return proto.CompactTextString(m) }
func (*TimeStamp) ProtoMessage()    {}
func (*TimeStamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eaed4801c3a9059, []int{3}
}

func (m *TimeStamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeStamp.Unmarshal(m, b)
}
func (m *TimeStamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeStamp.Marshal(b, m, deterministic)
}
func (m *TimeStamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeStamp.Merge(m, src)
}
func (m *TimeStamp) XXX_Size() int {
	return xxx_messageInfo_TimeStamp.Size(m)
}
func (m *TimeStamp) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeStamp.DiscardUnknown(m)
}

var xxx_messageInfo_TimeStamp proto.InternalMessageInfo

func (m *TimeStamp) GetValue() *timestamp.Timestamp {
	if m != nil {
		return m.Value
	}
	return nil
}

// An instance field of type DNSName denotes that the expression for the field must evaluate to
// [ValueType.DNS_NAME][echo.policy.v1alpha1.ValueType.DNS_NAME]
//
// Objects of type DNSName are also passed to the adapters during request-time for the instance fields of
// type DNSName
type DNSName struct {
	// DNSName encoded as string.
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DNSName) Reset()         { *m = DNSName{} }
func (m *DNSName) String() string { return proto.CompactTextString(m) }
func (*DNSName) ProtoMessage()    {}
func (*DNSName) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eaed4801c3a9059, []int{4}
}

func (m *DNSName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DNSName.Unmarshal(m, b)
}
func (m *DNSName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DNSName.Marshal(b, m, deterministic)
}
func (m *DNSName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DNSName.Merge(m, src)
}
func (m *DNSName) XXX_Size() int {
	return xxx_messageInfo_DNSName.Size(m)
}
func (m *DNSName) XXX_DiscardUnknown() {
	xxx_messageInfo_DNSName.DiscardUnknown(m)
}

var xxx_messageInfo_DNSName proto.InternalMessageInfo

func (m *DNSName) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// An instance field of type StringMap denotes that the expression for the field must evaluate to
// [ValueType.STRING_MAP][echo.policy.v1alpha1.ValueType.STRING_MAP]
//
// Objects of type StringMap are also passed to the adapters during request-time for the instance fields of
// type StringMap
type StringMap struct {
	// StringMap encoded as a map of strings
	Value                map[string]string `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *StringMap) Reset()         { *m = StringMap{} }
func (m *StringMap) String() string { return proto.CompactTextString(m) }
func (*StringMap) ProtoMessage()    {}
func (*StringMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eaed4801c3a9059, []int{5}
}

func (m *StringMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringMap.Unmarshal(m, b)
}
func (m *StringMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringMap.Marshal(b, m, deterministic)
}
func (m *StringMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringMap.Merge(m, src)
}
func (m *StringMap) XXX_Size() int {
	return xxx_messageInfo_StringMap.Size(m)
}
func (m *StringMap) XXX_DiscardUnknown() {
	xxx_messageInfo_StringMap.DiscardUnknown(m)
}

var xxx_messageInfo_StringMap proto.InternalMessageInfo

func (m *StringMap) GetValue() map[string]string {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*Value)(nil), "echo.policy.v1alpha1.Value")
	proto.RegisterType((*IPAddress)(nil), "echo.policy.v1alpha1.IPAddress")
	proto.RegisterType((*Duration)(nil), "echo.policy.v1alpha1.Duration")
	proto.RegisterType((*TimeStamp)(nil), "echo.policy.v1alpha1.TimeStamp")
	proto.RegisterType((*DNSName)(nil), "echo.policy.v1alpha1.DNSName")
	proto.RegisterType((*StringMap)(nil), "echo.policy.v1alpha1.StringMap")
	proto.RegisterMapType((map[string]string)(nil), "echo.policy.v1alpha1.StringMap.ValueEntry")
}

func init() {
	proto.RegisterFile("type.proto", fileDescriptor_8eaed4801c3a9059)
}

var fileDescriptor_8eaed4801c3a9059 = []byte{
	// 488 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xdf, 0x6e, 0xd3, 0x30,
	0x14, 0x87, 0xe3, 0x76, 0x5d, 0x97, 0x93, 0x52, 0xa6, 0x68, 0x17, 0x50, 0x89, 0x35, 0x1b, 0x37,
	0x11, 0x42, 0x0e, 0x2b, 0x08, 0x4d, 0x20, 0x24, 0x98, 0x98, 0x08, 0x20, 0x26, 0x94, 0x4e, 0x5c,
	0x70, 0x53, 0x39, 0x8d, 0x69, 0x2d, 0x92, 0x38, 0x4a, 0x9c, 0x4a, 0x79, 0x02, 0x5e, 0x80, 0x07,
	0x46, 0xf1, 0x9f, 0x74, 0x83, 0xb1, 0xdd, 0xc5, 0xa7, 0xdf, 0xf9, 0x7a, 0xce, 0xcf, 0x06, 0x10,
	0x4d, 0x41, 0x71, 0x51, 0x72, 0xc1, 0xdd, 0x03, 0xba, 0x5c, 0x73, 0x5c, 0xf0, 0x94, 0x2d, 0x1b,
	0xbc, 0x39, 0x21, 0x69, 0xb1, 0x26, 0x27, 0x93, 0xc3, 0x15, 0xe7, 0xab, 0x94, 0x06, 0x92, 0x89,
	0xeb, 0x1f, 0x41, 0x52, 0x97, 0x44, 0x30, 0x9e, 0xab, 0xae, 0xc9, 0xf4, 0xef, 0xdf, 0x05, 0xcb,
	0x68, 0x25, 0x48, 0x56, 0x28, 0xe0, 0xf8, 0xf7, 0x0e, 0x0c, 0xbe, 0x91, 0xb4, 0xa6, 0xee, 0x63,
	0x18, 0x55, 0xa2, 0x64, 0xf9, 0x6a, 0xb1, 0x69, 0xcf, 0x0f, 0x90, 0x87, 0x7c, 0x3b, 0xb4, 0x22,
	0x47, 0x55, 0x15, 0x74, 0x04, 0x0e, 0xcb, 0xc5, 0xcb, 0x17, 0x9a, 0xe9, 0x79, 0xc8, 0xef, 0x87,
	0x56, 0x04, 0xb2, 0xd8, 0x79, 0x12, 0x5e, 0xc7, 0x29, 0xd5, 0x4c, 0xdf, 0x43, 0x3e, 0x6a, 0x3d,
	0xaa, 0xaa, 0xa0, 0x29, 0x40, 0xcc, 0x79, 0xaa, 0x91, 0x1d, 0x0f, 0xf9, 0x7b, 0xa1, 0x15, 0xd9,
	0x6d, 0x4d, 0x01, 0x9f, 0x61, 0x9f, 0x15, 0x0b, 0x92, 0x24, 0x25, 0xad, 0x2a, 0x8d, 0x0d, 0x3c,
	0xe4, 0x3b, 0xb3, 0x29, 0xbe, 0x29, 0x09, 0xfc, 0xf1, 0xeb, 0x3b, 0x05, 0x87, 0x56, 0x34, 0x66,
	0x85, 0x3e, 0x28, 0xd9, 0x27, 0xb8, 0xdf, 0xed, 0xad, 0x5d, 0xbb, 0xb7, 0xb9, 0x2e, 0x59, 0x46,
	0xe7, 0x2d, 0xdc, 0xba, 0xba, 0x4e, 0xe5, 0xfa, 0x00, 0x63, 0x93, 0xb1, 0x56, 0x0d, 0xa5, 0xea,
	0xf0, 0x66, 0xd5, 0x7b, 0xcd, 0x86, 0x56, 0x74, 0xcf, 0xf4, 0x29, 0xd1, 0x39, 0x8c, 0x93, 0xbc,
	0x5a, 0xe4, 0x24, 0x33, 0x49, 0xd9, 0x52, 0xf4, 0xe8, 0x3f, 0xa2, 0x8b, 0xf9, 0x05, 0xc9, 0x68,
	0x68, 0x45, 0xa3, 0x24, 0xaf, 0xda, 0xcf, 0x2e, 0x28, 0x7d, 0x6d, 0x19, 0x31, 0xcb, 0x39, 0xb7,
	0x2d, 0x37, 0x97, 0xf4, 0x17, 0x22, 0x97, 0xab, 0xcc, 0x41, 0xca, 0xce, 0x86, 0x30, 0x90, 0x86,
	0xe3, 0x23, 0xb0, 0xbb, 0x40, 0xdd, 0x03, 0x5d, 0x95, 0x4f, 0x62, 0x14, 0x69, 0xe4, 0x35, 0xec,
	0x99, 0xe5, 0xdc, 0xe0, 0x2a, 0xe1, 0xcc, 0x1e, 0x62, 0xf5, 0xec, 0xb0, 0x79, 0x76, 0x5d, 0x0c,
	0xa6, 0xf9, 0x0d, 0xd8, 0x5d, 0xc8, 0xee, 0xb3, 0xeb, 0xdd, 0x93, 0x7f, 0xba, 0x2f, 0xcd, 0x15,
	0x98, 0xf6, 0x29, 0x0c, 0x75, 0x1e, 0xd7, 0x87, 0xb3, 0x0d, 0xf0, 0x0b, 0x81, 0xdd, 0x2d, 0xea,
	0xbe, 0xdd, 0x32, 0x7d, 0xdf, 0x99, 0x3d, 0xb9, 0x23, 0x18, 0x2c, 0xc3, 0x38, 0xcf, 0x45, 0xd9,
	0x68, 0xdf, 0xe4, 0x14, 0x60, 0x5b, 0x74, 0xf7, 0xa1, 0xff, 0x93, 0x36, 0xfa, 0x1f, 0xdb, 0xcf,
	0xed, 0x14, 0xbd, 0x2b, 0x53, 0xbc, 0xea, 0x9d, 0xa2, 0x33, 0xfc, 0xfd, 0xe9, 0x8a, 0x89, 0x75,
	0x1d, 0xe3, 0x25, 0xcf, 0x82, 0x25, 0xdf, 0x90, 0x92, 0x89, 0x26, 0x68, 0x27, 0x08, 0x48, 0xc1,
	0x02, 0x35, 0x45, 0x60, 0xa6, 0x88, 0x77, 0xe5, 0xd6, 0xcf, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff,
	0x78, 0xfd, 0x39, 0xba, 0xfc, 0x03, 0x00, 0x00,
}
