// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.11.4
// source: value_type.proto

package v1alpha1

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// ValueType describes the types that values in the Echo system can take. These
// are used to describe the type of Attributes at run time, describe the type of
// the result of evaluating an expression, and to describe the runtime type of
// fields of other descriptors.
type ValueType int32

const (
	// Invalid, default value.
	ValueType_VALUE_TYPE_UNSPECIFIED ValueType = 0
	// An undiscriminated variable-length string.
	ValueType_STRING ValueType = 1
	// An undiscriminated 64-bit signed integer.
	ValueType_INT64 ValueType = 2
	// An undiscriminated 64-bit floating-point value.
	ValueType_DOUBLE ValueType = 3
	// An undiscriminated boolean value.
	ValueType_BOOL ValueType = 4
	// A point in time.
	ValueType_TIMESTAMP ValueType = 5
	// An IP address.
	ValueType_IP_ADDRESS ValueType = 6
	// An email address.
	ValueType_EMAIL_ADDRESS ValueType = 7
	// A URI.
	ValueType_URI ValueType = 8
	// A DNS name.
	ValueType_DNS_NAME ValueType = 9
	// A span between two points in time.
	ValueType_DURATION ValueType = 10
	// A map string -> string, typically used by headers.
	ValueType_STRING_MAP ValueType = 11
)

// Enum value maps for ValueType.
var (
	ValueType_name = map[int32]string{
		0:  "VALUE_TYPE_UNSPECIFIED",
		1:  "STRING",
		2:  "INT64",
		3:  "DOUBLE",
		4:  "BOOL",
		5:  "TIMESTAMP",
		6:  "IP_ADDRESS",
		7:  "EMAIL_ADDRESS",
		8:  "URI",
		9:  "DNS_NAME",
		10: "DURATION",
		11: "STRING_MAP",
	}
	ValueType_value = map[string]int32{
		"VALUE_TYPE_UNSPECIFIED": 0,
		"STRING":                 1,
		"INT64":                  2,
		"DOUBLE":                 3,
		"BOOL":                   4,
		"TIMESTAMP":              5,
		"IP_ADDRESS":             6,
		"EMAIL_ADDRESS":          7,
		"URI":                    8,
		"DNS_NAME":               9,
		"DURATION":               10,
		"STRING_MAP":             11,
	}
)

func (x ValueType) Enum() *ValueType {
	p := new(ValueType)
	*p = x
	return p
}

func (x ValueType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValueType) Descriptor() protoreflect.EnumDescriptor {
	return file_value_type_proto_enumTypes[0].Descriptor()
}

func (ValueType) Type() protoreflect.EnumType {
	return &file_value_type_proto_enumTypes[0]
}

func (x ValueType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValueType.Descriptor instead.
func (ValueType) EnumDescriptor() ([]byte, []int) {
	return file_value_type_proto_rawDescGZIP(), []int{0}
}

var File_value_type_proto protoreflect.FileDescriptor

var file_value_type_proto_rawDesc = []byte{
	0x0a, 0x10, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x14, 0x65, 0x63, 0x68, 0x6f, 0x2e, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2e,
	0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2a, 0xbb, 0x01, 0x0a, 0x09, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x16, 0x56, 0x41, 0x4c, 0x55, 0x45, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x09,
	0x0a, 0x05, 0x49, 0x4e, 0x54, 0x36, 0x34, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x4f, 0x55,
	0x42, 0x4c, 0x45, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x42, 0x4f, 0x4f, 0x4c, 0x10, 0x04, 0x12,
	0x0d, 0x0a, 0x09, 0x54, 0x49, 0x4d, 0x45, 0x53, 0x54, 0x41, 0x4d, 0x50, 0x10, 0x05, 0x12, 0x0e,
	0x0a, 0x0a, 0x49, 0x50, 0x5f, 0x41, 0x44, 0x44, 0x52, 0x45, 0x53, 0x53, 0x10, 0x06, 0x12, 0x11,
	0x0a, 0x0d, 0x45, 0x4d, 0x41, 0x49, 0x4c, 0x5f, 0x41, 0x44, 0x44, 0x52, 0x45, 0x53, 0x53, 0x10,
	0x07, 0x12, 0x07, 0x0a, 0x03, 0x55, 0x52, 0x49, 0x10, 0x08, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x4e,
	0x53, 0x5f, 0x4e, 0x41, 0x4d, 0x45, 0x10, 0x09, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x55, 0x52, 0x41,
	0x54, 0x49, 0x4f, 0x4e, 0x10, 0x0a, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47,
	0x5f, 0x4d, 0x41, 0x50, 0x10, 0x0b, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x76, 0x61, 0x72, 0x69, 0x74, 0x79, 0x2f, 0x65, 0x63,
	0x68, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2f, 0x76, 0x31,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_value_type_proto_rawDescOnce sync.Once
	file_value_type_proto_rawDescData = file_value_type_proto_rawDesc
)

func file_value_type_proto_rawDescGZIP() []byte {
	file_value_type_proto_rawDescOnce.Do(func() {
		file_value_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_value_type_proto_rawDescData)
	})
	return file_value_type_proto_rawDescData
}

var file_value_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_value_type_proto_goTypes = []interface{}{
	(ValueType)(0), // 0: echo.policy.v1alpha1.ValueType
}
var file_value_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_value_type_proto_init() }
func file_value_type_proto_init() {
	if File_value_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_value_type_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_value_type_proto_goTypes,
		DependencyIndexes: file_value_type_proto_depIdxs,
		EnumInfos:         file_value_type_proto_enumTypes,
	}.Build()
	File_value_type_proto = out.File
	file_value_type_proto_rawDesc = nil
	file_value_type_proto_goTypes = nil
	file_value_type_proto_depIdxs = nil
}
